# Docker CI/CD Pipeline (Optional - for containerized deployment)
# This workflow is disabled by default since we're using GitHub Pages
# To enable: remove the "if: false" condition and set up Docker Hub secrets

name: Frontend CI/CD Pipeline

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    if: false  # Disabled - remove this line to enable Docker builds
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
       driver: docker
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set Docker tag
      id: set-tag
      run: |
        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
          echo "TAG=latest" >> $GITHUB_OUTPUT
        else
          echo "TAG=dev" >> $GITHUB_OUTPUT
        fi
    
    - name: Build and push frontend
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-portfolio:${{ steps.set-tag.outputs.TAG }}   

